/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplosw;

import javax.swing.JOptionPane;
import java.sql.SQLException;

/**
 *
 * @author salva
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Agenda - Salva");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JSpinner();
        jDNI = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        bHombre = new javax.swing.JCheckBox();
        bMujer = new javax.swing.JCheckBox();
        bOtro = new javax.swing.JCheckBox();
        guardar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        verDatos = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        CBTipoEnfermedad = new javax.swing.JComboBox<>();
        jTipoEnfermedad = new javax.swing.JLabel();
        jNombreEnfermedad = new javax.swing.JLabel();
        txtNombreEnfermedad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CBGravedad = new javax.swing.JComboBox<>();
        jDias = new javax.swing.JLabel();
        txtDias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO");

        jNombre.setText("Nombre:");

        jApellidos.setText("Apellidos:");

        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        jEdad.setText("Edad:");

        jDNI.setText("DNI:");

        bHombre.setText("Hombre");

        bMujer.setText("Mujer");

        bOtro.setText("Otro");

        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        verDatos.setText("Consultar");
        verDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                verDatosMouseClicked(evt);
            }
        });

        CBTipoEnfermedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enfermedad Muscular ", "Enfermedad Infecciosa" }));

        jTipoEnfermedad.setText("Tipo Enfermedad:");

        jNombreEnfermedad.setText("Nombre Enfermedad:");

        txtNombreEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEnfermedadActionPerformed(evt);
            }
        });

        jLabel2.setText("Gravedad:");

        CBGravedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jDias.setText("Días Reposo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jNombreEnfermedad)
                            .addComponent(jLabel2)
                            .addComponent(jDias))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBGravedad, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verDatos)
                .addGap(174, 174, 174))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jApellidos)
                            .addComponent(jNombre)
                            .addComponent(jEdad)
                            .addComponent(jDNI)
                            .addComponent(bHombre)
                            .addComponent(jTipoEnfermedad))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBTipoEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(bMujer)
                                    .addGap(34, 34, 34)
                                    .addComponent(bOtro))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(txtApellidos)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDNI)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHombre)
                    .addComponent(bMujer)
                    .addComponent(bOtro))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBTipoEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTipoEnfermedad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEnfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNombreEnfermedad))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBGravedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDias)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(borrar)
                    .addComponent(verDatos))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarActionPerformed

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        String dni = txtDni.getText();
        int tam = dni.length();
        //Recogemos el campos eleccionado por el usuario en un combobox
        //y lo almacenamos en una variable para instanciar la clase persona
        String tipoEn = (String) CBTipoEnfermedad.getSelectedItem();
        String tipoG = (String) CBGravedad.getSelectedItem();
        int tipoGr = Integer.parseInt(tipoG);
        //Comprobamosq ue todos los campos esten introducidos
        if (txtNombre.equals("") || txtApellidos.equals("") || txtDni.equals("") || tam < 9 || tam > 9
                || txtNombreEnfermedad.equals("")) {
            JOptionPane.showMessageDialog(null, "Algún campo incompleto o DNI Incorrecto");
        } else {
            int diasAprox = calcularDias(tipoEn, tipoGr);
            String numDias = String.valueOf(diasAprox);
            txtDias.setText(numDias);

            sql modSql = new sql();
            //Clase Persona
            Persona mod = new Persona();
            mod.setNombre(txtNombre.getText());
            mod.setApellidos(txtApellidos.getText());
            mod.setEdad((Integer) txtEdad.getValue());
            mod.setDni(txtDni.getText());
            mod.setHombre(bHombre.isSelected());
            mod.setMujer(bMujer.isSelected());
            mod.setOtro(bOtro.isSelected());
            mod.setTipoEnfermedad(tipoEn);
            mod.setNombreEnfermedad(txtNombreEnfermedad.getText());
            mod.setGravedad(tipoGr);
            mod.setDias(diasAprox);

            //Excepcion por si el usuario no se ha creado correctamente
            try {
                if (modSql.registro(mod)) { //Aqui guardo los registros en la base de datos 
                    JOptionPane.showMessageDialog(null, "Usuario creado correctamente!");
                    limpiarRegistros();
                }
            } catch (SQLException ext) {
                JOptionPane.showMessageDialog(null, "Ha habido un problema conectando a la base de datos!!");

            }

        }
    }//GEN-LAST:event_guardarMouseClicked

    private void txtNombreEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEnfermedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEnfermedadActionPerformed
    //Aqui limpiamos todos los campos dejandolo vacios despues de guardarlo
    public void limpiarRegistros() {
        txtNombreEnfermedad.setText(" ");
        txtNombre.setText("");
        txtDni.setText("");
        txtApellidos.setText("");
        txtEdad.setValue(0);
    }
    private void verDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verDatosMouseClicked
        String DNI = JOptionPane.showInputDialog("Introduce el DNI del paciente al que quieres consultar, por favor!");
        Consulta c = new Consulta(DNI);
        try {
            if (c.registro()) {
                String mensaje = "<html><body>DATOS DEL DNI:<br> " + DNI + "<br> <br> Nombre: " + c.getNombre() + " <br> Enfermedad: " + c.getNombreEnfermedad() + "<br> Días de reposo: " + c.getDias() + "</body></html>";
                JOptionPane.showMessageDialog(null, mensaje);
            }
        } catch (SQLException ext) {
            JOptionPane.showMessageDialog(null, "Ha habido un problema conectando a la base de datos!!");

        }    }//GEN-LAST:event_verDatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBGravedad;
    private javax.swing.JComboBox<String> CBTipoEnfermedad;
    private javax.swing.JCheckBox bHombre;
    private javax.swing.JCheckBox bMujer;
    private javax.swing.JCheckBox bOtro;
    private javax.swing.JButton borrar;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jApellidos;
    private javax.swing.JLabel jDNI;
    private javax.swing.JLabel jDias;
    private javax.swing.JLabel jEdad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jNombreEnfermedad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jTipoEnfermedad;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JLabel txtDias;
    private javax.swing.JTextField txtDni;
    private javax.swing.JSpinner txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEnfermedad;
    private javax.swing.JButton verDatos;
    // End of variables declaration//GEN-END:variables

    //Aqui calculamos el numero de dias segun la gravedad de la enfermedad
    private int calcularDias(String tipoEn, int tipoGr) {

        int dias = 0;
        if (tipoEn.equals("Enfermedad Infecciosa")) {
            if (tipoGr == 1) {
                dias = 7;
            } else if (tipoGr == 2) {
                dias = 14;
            } else if (tipoGr == 3) {
                dias = 30;
            }
        }
        if (tipoEn.equals("Enfermedad Muscular")) {
            if (tipoGr == 1) {
                dias = 10;
            } else if (tipoGr == 2) {
                dias = 25;
            } else if (tipoGr == 3) {
                dias = 40;
            }
        }
        return dias;
    }

}
